apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automatizase

resources:
  - configmap.yaml
  - deployment-server.yaml
  - deployment-mcp.yaml
  - deployment-agents.yaml
  - deployment-frontend.yaml
  - service-server.yaml
  - service-mcp.yaml
  - service-agents.yaml
  - service-frontend.yaml
  - ingress.yaml

commonLabels:
  app: archon
  app.kubernetes.io/name: archon
  app.kubernetes.io/managed-by: argocd
