apiVersion: v1
kind: Service
metadata:
  name: archon-server
  namespace: unlkd
  labels:
    app.kubernetes.io/name: archon-server
    app.kubernetes.io/instance: archon
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8181
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: archon-server
    app.kubernetes.io/instance: archon
