apiVersion: v1
kind: Service
metadata:
  name: archon-frontend
  namespace: unlkd
  labels:
    app.kubernetes.io/name: archon-frontend
    app.kubernetes.io/instance: archon
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3737
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: archon-frontend
    app.kubernetes.io/instance: archon
